//WRITE A C PROGRAM TO CALCULATE AVERAGE OF FIRST N NUMBERS USING DO WHILE LOOP
//WRITE A C PROGRAM TO PRINT THE MULTIPLIOCATION TABLE OF A GIVEN NUMBER UPTO 10 NUMBERS USING THE FOR LOOP

#include<stdio.h>
int main(){

	int number,i,n;
	

